spring.application.name: sky-inDay

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/funcdb
    username: postgres
    password: zhangyvjing
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
